### ISSUE TITLE
Support push based connection

### ISSUE THREAD

**Issue by amosyuen** [pszafer/epson_projector#13]
Seems like the implementation is polling based, reading data only after sending a request and closing the connection after the timeout. I would like to see an option for an implementation that keeps the connection open to get pushes for changes. 

Not sure if that's possible over HTTP, but definitely should be possible using TCP sockets for the latest home cinema series epson projectors. I implemented this successfully in hubitat https://github.com/amosyuen/hubitat/blob/main/epson/Epson%20Projector.groovy.

Happy to help with code, but am unfamiliar with python async code.

**Comment by pszafer** [comment]
I tested it already last year. Many projectors doesn't respond to TCP connection commands, so for commands I'd need to fallback to HTTP. I don't want to make integration work with only newer projectors.
The best option would be to somehow detect projector model no and then make different approaches of connection, but I couldn't find any way to retrieve projector model or find model from serial number

**Comment by amosyuen** [comment]
Why not just let the user set it? You can default to http, but have an option to change it to TCP.

But even looking at your TCP code, it looks like it is polling based.

**Comment by pszafer** [comment]
Average user doesn't know difference between TCP and HTTP and I never wanted to make this integration only for "professionals".
TCP is polling because right now I'm only fetching serial no over it and during tests with other users many projector didn't send `IMEVENT`
Anyway, I can try to make custom_component first with all features needed (TCP polling, serial polling) and then maybe we can figure out how to make it easy to user to add so it can be presented in official integration

**Comment by amosyuen** [comment]
Deduping to https://github.com/pszafer/epson_projector/issues/11
